### ISSUE TITLE
Add more examples of umbrella organisations

### ISSUE THREAD

**Issue by silverhook** [FOSSmarks/FOSSmarks#6]
It might make sense to further enhance the list of umbrella organisations to bring more balance into it.

Some additional umbrella organisations OTOH, happy to have this list extended as well:

- Software In Public Interest (US) – https://www.spi-inc.org/
- Public Software CIC (UK) – https://publicsoftware.eu/
- The Commons Conservancy (NL) – http://commonsconservancy.org/
- Center for the Cultivation of Technology (DE) – https://techcultivation.org/

**Comment by westonkdavis** [comment]
I agree, and think this list can probably be expanded. We then need to decide what section to incorporate the list into.

**Comment by pchestek** [comment]
Entities added
